name: parent_5sur5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  animated_text_kit: ^4.2.2
  internet_connection_checker: ^3.0.1
  audioplayers: ^6.4.0
  video_player: ^2.9.5
  just_audio: ^0.10.3
  chewie: ^1.11.3
  http: ^1.4.0 
  intl: 0.19.0  # Version unique et cohérente (suppression de la duplication)
  flutter_localizations:
    sdk: flutter  # Ajout essentiel pour les locales
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/game1.jpg
    - assets/images/game2.jpg
    - assets/images/game3.jpg
    - assets/images/logo.png
    - assets/images/paint1.jpg
    - assets/images/paint2.jpg